### PR TITLE
Full support for linux (not editing, only shader loading)

### PR DESCRIPTION
**Pull request by 0xBADEAFFE**

### CODE REVIEW

**Comment by Biohazard90** [comment]
Thanks, this is great! I am a bit swamped at the moment but I'll check it out as soon as I am free.

**Comment by 0xBADEAFFE** [comment]
@Biohazard90 Do you have any idea how to force only _vs20 / _ps20b shader loading because only these shaders are working on linux.

**Comment by Biohazard90** [comment]
@vincent-t Are you talking about automatically compiling a shader for multiple targets, so that Windows could load the sm 3.0 version and Linux would be able to fall back to the sm 2.0 one (and convert it to GLSL)?

Or would it be sufficient to just compile for sm 2.0 across the board, so that it works on all platforms?

**Comment by 0xBADEAFFE** [comment]
@Biohazard90 Compiling multiple targets would be great. Only issue at the moment if both shaders are present Linux also preferes sm 3.0 but throws a GLSL translation error. How can er force Linux to use the sm 2.0 version without renaming them.

**Comment by Biohazard90** [comment]
@vincent-t Ah I see. You could force it in procshader.cpp by passing a different string to pShaderShadow->SetVertexShader() and pShaderShadow->SetPixelShader() if you're compiling for Linux. Since this isn't called per frame, it would be okay to just copy the string and replace the suffix locally.

A better solution would be to compile for both targets in a legit manner and pass all shader names to the shader implementation (procshader.cpp), so it can automatically fall back (or in case of Linux, always fall back) to sm 2.0. You could probably add additional compiler jobs for sm 2.0, if the user selected sm 3.0 as the target and a full compile was requested.

Maybe you could duplicate the message in void CAutoSolverCallback::UploadCompilationRequest() and change the shader model target to sm 2.0 so that it actually compiles for two targets, but I'm not familiar enough with the code anymore to say for sure.

**Comment by 0xBADEAFFE** [comment]
@Biohazard90 I've managed to load the sm 2.0 shaders without renaming but if the sm 3.0 shaders are present they still get loaded.

```
#ifdef _WIN32
            pShaderShadow->SetVertexShader( cfg->ProcVSName, index_vs_static );
            pShaderShadow->SetPixelShader( cfg->ProcPSName, index_ps_static );
#else // POSIX
            char tmp_vs[MAX_PATH*4];
            char tmp_ps[MAX_PATH*4];
            V_strncpy(tmp_vs, cfg->ProcVSName, sizeof( tmp_vs ) );
            V_strncpy(tmp_ps, cfg->ProcPSName, sizeof( tmp_ps ) );
            //Msg( "VertexShader name: %s.\n", tmp_vs );
            //Msg( "PixelShader name: %s.\n", tmp_ps );
            char * tmp_p_vs;
            char * tmp_p_ps;
            tmp_p_vs = V_strstr( tmp_vs, "_vs30" );
            tmp_p_ps = V_strstr( tmp_ps, "_ps30" );
            V_strncpy( tmp_p_vs, "_vs20", 7 );
            V_strncpy( tmp_p_ps, "_ps20b", 7 );
            //Msg( "PS 2.0 VertexShader name: %s.\n", tmp_vs );
            //Msg( "PS 2.0 PixelShader name: %s.\n", tmp_ps );
            // load ps2.0 shaders
            pShaderShadow->SetVertexShader( tmp_vs, index_vs_static );
            pShaderShadow->SetPixelShader( tmp_ps, index_ps_static );
#endif // POSIX
```

**Comment by Biohazard90** [comment]
@vincent-t Did you manage to find a fix? I can't think of any other statements that could invoke loading of the wrong .vcs files in the material system other than the two lines I mentioned.

**Comment by 0xBADEAFFE** [comment]
@Biohazard90 Yes, I found a fix to force sm 2.0 under Linux(https://github.com/vincent-t/source-shader-editor/commit/e5aab90042919db09b8c0ef65110b0467fa61a47).

**Comment by 0xBADEAFFE** [comment]
@Biohazard90 Currently I struggle loading the shaders from .vpk files, it only works if the .dumps, canvas and postprocessing_precache.txt is not packaged inside the .vpk. Do you have any idea to solve this?

**Comment by Biohazard90** [comment]
@vincent-t My guess is that you need to replace the "MOD" tag in all occurrences of file open/read operations. Try using "GAME", empty string or null.

**Comment by 0xBADEAFFE** [comment]
@Biohazard90 Thank's, got it working! :+1:

**Pull request closed without merging**
